apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: jenkins-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30009
      name: http