apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
spec:
  storageClassName: standard
  claimRef:
    name: jenkins-pv-claim
    namespace: devops-tools
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt